nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.4.cjs

npmRegistryServer: 'https://prod-nexus.sprinklr.com/nexus/repository/npm/'
npmAlwaysAuth: true
npmAuthIdent: 'developers:iOgwLCf8vmOb'
npmAuditRegistry: 'https://registry.yarnpkg.com'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

logFilters:
  - code: YN0013
    level: discard
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0057
    level: discard
  - code: YN0007
    level: discard
  - code: YN0008
    level: discard
